apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: "snimark/103"
  name: "onezerothree-0"
  namespace: snimark
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: "snimark/103"
  type: LoadBalancer
status:
  loadBalancer: {}
