apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: "103"
  name: "onezerothree-0"
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: "103"
status:
  loadBalancer: {}
